spring.application.name=gateway-service
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

app.jwt.secret=${JWT_SECRET:velvet-gilt-dev-secret-cambiar-en-produccion-0123456789}
app.jwt.ttl-minutes=1440

management.endpoints.web.exposure.include=health,info

spring.cloud.gateway.server.webflux.routes[0].id=auth
spring.cloud.gateway.server.webflux.routes[0].order=10
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.server.webflux.routes[0].uri=lb://auth-service

spring.cloud.gateway.server.webflux.routes[1].id=users
spring.cloud.gateway.server.webflux.routes[1].order=20
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/users/**
spring.cloud.gateway.server.webflux.routes[1].uri=lb://auth-service

spring.cloud.gateway.server.webflux.routes[2].id=notification
spring.cloud.gateway.server.webflux.routes[2].order=30
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/notifications/**
spring.cloud.gateway.server.webflux.routes[2].uri=lb://notification-service

spring.cloud.gateway.server.webflux.routes[3].id=public
spring.cloud.gateway.server.webflux.routes[3].order=40
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/public/**
spring.cloud.gateway.server.webflux.routes[3].uri=lb://core-service

spring.cloud.gateway.server.webflux.routes[4].id=core
spring.cloud.gateway.server.webflux.routes[4].order=50
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/**
spring.cloud.gateway.server.webflux.routes[4].uri=lb://core-service

eureka.instance.hostname=localhost
